version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: skud-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: skud_db
      POSTGRES_USER: skud_user
      POSTGRES_PASSWORD: skud_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql_init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - skud-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skud_user -d skud_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API сервис
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: skud-backend
    restart: unless-stopped
    expose:
      - "8003"
    volumes:
      # Монтируем базу данных SQLite для fallback
      - ./real_skud_data.db:/app/real_skud_data.db
      # Монтируем конфигурации
      - ./real_skud_config.ini:/app/real_skud_config.ini
      - ./postgres_config.ini:/app/postgres_config.ini
      # Монтируем директории для загрузки данных
      - ./data_input:/app/data_input
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://skud_user:skud_password_2024@postgres:5432/skud_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - skud-network

  # Frontend сервис
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: skud-frontend
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=/api
    depends_on:
      - backend
    networks:
      - skud-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: skud-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - skud-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  skud-network:
    driver: bridge

# Постоянные тома для данных
volumes:
  postgres_data:
    driver: local