version: '3.8'

services:
  skud-app:
    build: .
    container_name: skud-monitor
    restart: unless-stopped
    volumes:
      # Монтируем директории для данных
      - ./real_data_input:/app/real_data_input
      - ./processed_real_skud:/app/processed_real_skud
      - ./backups:/app/backups
      # Монтируем базу данных (если используется SQLite)
      - ./real_skud_data.db:/app/real_skud_data.db
      # Монтируем конфигурационный файл
      - ./real_skud_config.ini:/app/real_skud_config.ini
      # Монтируем логи
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    # Если нужен веб-интерфейс
    # ports:
    #   - "8000:8000"
    
  # Опциональный сервис для PostgreSQL (если нужно)
  # postgres:
  #   image: postgres:15
  #   container_name: skud-postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: skud_db
  #     POSTGRES_USER: skud_user
  #     POSTGRES_PASSWORD: your_password_here
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: